deaconn/blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.blog_view, name = 'index'),
    path('<int:article_id>-<slug:slug>/', views.article_view, name = 'article'),
    path('create_article/', views.create_article, name = 'create_article')
]

deaconn/deaconn/urls.py
from django.contrib import admin
from django.urls import include, path

from home.views import home_view
from home.views import convert_with_markdown

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view),
    path('do_markdown/', convert_with_markdown),
    path('products/', include('products.urls')),
    path('blog/', include('blog.urls')),
    path('tmc/', include('tmc.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

deaconn/tmc/urls.py
from django.urls import path

from .views import tmc_view

app_name = 'tmc'
urlpatterns = [
    path('', tmc_view, name = 'index')
]

deaconn/blog/models.py
from django.db import models
from django.contrib.auth.models import User

from django.template.defaultfilters import slugify

from django.core.files.storage import default_storage

import string
import random

def file_path(instance, filename):
    str = ''

    while True:
        str = ''.join(random.choices(string.ascii_letters + string.digits, k = 8))

        if not default_storage.exists(str):
            break

    return str + '.' + filename.rsplit('.', 1)[1]

class Article(models.Model):
    author = models.ForeignKey(User, on_delete = models.CASCADE)
    date_added = models.DateTimeField(editable = False, auto_now_add = True)
    date_updated = models.DateTimeField(editable = False, auto_now = True)

    title = models.CharField(verbose_name = "Title", help_text = "The title of the article.", max_length = 128)
    tags = models.CharField(verbose_name = "Tags", help_text = "Tags for this article.", max_length = 255)
    description = models.TextField(verbose_name = "Description", help_text = "Text shown on the main blog page for article.", max_length = 255)

    contents = models.TextField(verbose_name = "Contents", help_text = "The article content.", max_length = 1000000)

    image = models.ImageField(verbose_name = "Header Image", upload_to = file_path, blank = True)

    slug = models.SlugField(slugify('slug'), max_length = 60, blank = True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)

        super().save(*args, **kwargs)

        if self.id:
            # Delete current tags associated with this article.
            Article_Tags.objects.filter(article = self).delete()

            # Loop through each tag.
            tags = self.tags.split(',')

            for tag in tags:
                category = False

                tag = tag.strip()

                if tag.startswith('|'):
                    category = True
                    tag = tag[1:]

                new_tag = Tags.objects.get_or_create(name = tag)

                # Insert tag for article.
                Article_Tags.objects.create(article = self, tag = new_tag[0], category = category)
                    
class Tags(models.Model):
    name = models.CharField(unique = True, verbose_name = "Name", help_text = "Name of tag.", max_length = 64)
    description = models.TextField(verbose_name = "Description", help_text = "The tag description.", max_length = 255)

class Article_Tags(models.Model):
    article = models.ForeignKey(Article, on_delete = models.CASCADE)
    tag = models.ForeignKey(Tags, on_delete = models.CASCADE)
    category = models.BooleanField(default = False)

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete = models.CASCADE)

    author = models.ForeignKey(User, on_delete = models.CASCADE)
    date_added = models.DateTimeField(auto_now_add = True)
    date_updated = models.DateTimeField(auto_now = True)

    contents = models.TextField(max_length = 10096)

deaconn/blog/views.py
from distutils.log import info
from django.shortcuts import render
from . import models
from django.conf import settings

from django.template.defaultfilters import slugify
from django.db.models import Q

from django.contrib.auth.models import User

def blog_view(request):
    info = {}

    page = request.GET.get('p', 1)
    search = request.GET.get('s', None)

    # Common information.
    info["template_name"] = 'blog/blog.html'
    info["title"] = 'Blog - Deaconn'

    # Retrieve articles list.
    articles = models.Article.objects.all()

    if search is not None:
        articles = articles.filter(Q(tags__icontains = search) | Q(description__icontains = search) | Q(title__icontains = search) | Q(contents__icontains = search))

    info["articles_count"] = articles.count()

    category_tags = models.Article_Tags.objects.filter(category = True)
    info["ctags"] = {}

    for ct in category_tags:
        if ct.tag.name not in info["ctags"]:
            info["ctags"][ct.tag.name] = 1
        else:
            info["ctags"][ct.tag.name] = info["ctags"][ct.tag.name] + 1

    info["ctags"] = {k: v for k, v in sorted(info["ctags"].items(), reverse = True, key = lambda item: item[1])}

    start_idx = (int(page) * settings.BLOG_MAX_PER_PAGE) - settings.BLOG_MAX_PER_PAGE
    end_idx = (int(page) * settings.BLOG_MAX_PER_PAGE)

    info["page_num"] = page

    info["pages"] = []

    if info["articles_count"] > settings.BLOG_MAX_PER_PAGE:
        page_cnt = int(info["articles_count"] / settings.BLOG_MAX_PER_PAGE)
        for i in range(page_cnt):
            info["pages"].append(i + 1)

    info["articles"] = articles.order_by('-date_added')[start_idx:end_idx]

    return render(request, 'home/page.html', info)

def article_view(request, article_id = None, slug = None):
    # Check if incoming comment.
    info = {}

    # Retrieve article
    try:
        info["article"] = models.Article.objects.get(id = article_id)
    except Exception:
        info["article"] = False

    if request.method == "POST" and request.user.is_authenticated:
        # Check to make comment.
        if 'add_comment_contents' in request.POST and len(request.POST['add_comment_contents']) > 15:
            models.Comment.objects.create(article = info["article"], author = request.user, contents = request.POST['add_comment_contents'])
            info["comment_successful"] = True
        
        # Check for article or comment edits.
        if 'article_edit' in request.POST:
            if info["article"] and (info["article"].author.id == request.user.id or request.user.is_staff):
                info["article_edit"] = True

        # Next check for edited fields.
        if 'article_title' in request.POST:
            if info["article"] and (info["article"].author.id == request.user.id or request.user.is_staff):
                info["article"].title = request.POST['article_title']
                info["article"].description = request.POST['article_description']
                info["article"].tags = request.POST['article_tags']
                info["article"].contents = request.POST['article_contents']

                if 'article_image' in request.FILES:
                    info["article"].image = request.FILES['article_image']
                elif 'article_image_del' in request.POST:
                    info["article"].image = None

                info["article"].save()
                info["article_edited"] = True

        # Check for comment edit.
        if 'comment_edit' in request.POST:
            id = request.POST['comment_id']
            
            try:
                comment = models.Comment.objects.get(id = id)
            except Exception:
                comment = False

            if comment and (comment.author.id == request.user.id or request.user.is_staff):
                info["comment_edit"] = True

        # Next check for edited fields.
        if 'comment_contents' in request.POST:
            id = request.POST['comment_id']
            
            try:
                comment = models.Comment.objects.get(id = id)
            except Exception:
                comment = False

            if comment and (comment.author.id == request.user.id or request.user.is_staff):
                comment.contents = request.POST['comment_contents']
                comment.save()
                info["comment_edited"] = True

        # Check for article delete.
        if 'article_delete' in request.POST:
            if info["article"] and (info["article"].author.id == request.user.id or request.user.is_staff):
                models.Article.objects.filter(id = info["article"].id).delete()
                info["article_deleted"] = True

        # Check for comment delete.
        if 'comment_delete' in request.POST:
            id = request.POST['comment_id']
            
            try:
                comment = models.Comment.objects.get(id = id)
            except Exception:
                comment = False

            if comment and (comment.author.id == request.user.id or request.user.is_staff):
                models.Comment.objects.get(id = id).delete()
                info["comment_deleted"] = True

    info["user"] = request.user

    # Common information.
    info["template_name"] = 'blog/view_article.html'
    info["title"] = 'Blog - Deaconn'

    if not info["article"].slug:
        info["article"].slug = slugify(info["article"].title)
        info["article"].save()

    if info["article"] != False:
        # Retrieve comments.
        info["comments"] = models.Comment.objects.filter(article = info["article"])

        # Fill out other information.
        info["title"] = info["article"].title
        info["tags"] = info["article"].tags
        info["description"] = info["article"].description
        info["author"] = info["article"].author.first_name + " " + info["article"].author.last_name

    return render(request, 'home/page.html', info)

def create_article(request):
    info = {}

    if 'article_title' in request.POST:
        if request.user and request.user.is_authenticated:
            item = models.Article.objects.create(author = request.user, title = request.POST['article_title'], tags = request.POST['article_tags'], description = request.POST['article_description'], contents = request.POST['article_contents'])

            if 'article_image' in request.FILES:
                item.image = request.FILES['article_image']
                item.save()
            
            info["article_added"] = True

    info["title"] = "Create Article"
    info["template_name"] = 'blog/create_article.html'
    info["user"] = request.user

    return render(request, 'home/page.html', info)

deaconn/blog/templates/blog/blog.html
{% load static %}
{% load tags %}
{% load markdown %}

{% if articles.count > 0 %}
    <div class="row row-cols-1 row-cols-md-2 g-4">
        <div class="col">
            <div class="card" id="search-n-ctags">
                <div class="card-body">
                    <div class="row">
                        <div class="col col-sm=12 col-md-6">
                            <h3 class="text-center">Search</h3>
                            <form action="{% url 'blog:index' %}" method="GET">
                                <div class="form-group">
                                    <input type="text" class="form-control" id="search" name="s" />
                                </div>
                                <br />
                                <div class="text-center">
                                    <button class="btn btn-primary post-btn" type="submit">Search!</button>
                                </div>
                            </form>
                        </div>

                        {% if ctags %}
                            <div class="col col-sm=12 col-md-6">
                                <h3 class="text-center">Categories</h3>
                                <ul id="ctags">
                                    {% for k,v in ctags.items %}
                                        <li class="align-items-center"><a href="{% url 'blog:index' %}?s={{ k }}">{{ k }} ({{ v }})</a></li>
                                    {% endfor %}
                                </ul>
                            </div> 
                        {% endif %}
                    </div>
                    {% if user and user.is_authenticated %}
                        <div class="row" id="article_add_div">
                            <div class="col text-center">
                                <a href="{% url 'blog:create_article' %}"><i class="bi bi-file-plus-fill"></i></a>
                            </div>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>

        {% for article in articles %}
            <div class="col">
                <div class="card">
                    <img class="card-img-top" src="{% if article.image %}{{ article.image.url }}{% else %}{% static 'home/default_banner.jpg' %}{% endif %}" alt="header image">
                    <div class="card-body">
                        <h1 class="card-title text-center">{{ article.title }}</h1>

                        <p class="card-text">
                            <small>By <span class="flair">{% if article.author.first_name %}{{ article.author.first_name }} {{ article.author.last_name }}{% else %}{{ article.author.username }}{% endif %}</span></small>
                            <br />
                            <small>Created On <span class="flair">{{ article.date_added }}</span></small>
                        </p>
                        <div class="markdown card-text">
                            {{ article.description | do_markdown }}
                        </div>
                        
                        <br />
                        <div class="text-center tags"><p class="card-text">{{ article | do_tags }}</p></div>
                        <br />
                        <p class="card-text"><h3 class="text-center"><a href="{% url 'blog:article' article_id=article.id slug=article.slug %}">Read full article!</a></h3></p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    {% if pages %}
        <div class="row">
            <div class="col">
                <div class="text-center">
                    {% for page in pages %}
                        <span class="page{% if page|stringformat:'s' == page_num|stringformat:'s' %} active{% endif %}"><a href="/blog?p={{ page }}">{{ page }}</a></span>
                    {% endfor %}
                </div>
            </div>
        </div>
    {% endif %}
{% else %}
        <p><h3 class="text-center">No Articles Found!</h3></p>
{% endif %}
    

deaconn/blog/templates/blog/create_article.html
{% load static %}
{% load markdown %}
{% load user_avatar %}

{% if user and user.is_authenticated %}
    {% if article_added %}
        <script type="text/javascript">notify("Article made successfully!");</script>
    {% endif %}

    <div class="row">
        <div class="col-md-12 col-lg-12">
            <div class="card">
                <img class="card-img-top" src="{% static 'home/default_banner.jpg' %}" alt="header image">
                <div class="card-body">
                    <div id="article_edit">
                        <form action="{% url 'blog:create_article' %}" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col">
                                    <div class="form-group">
                                        <label for="article_title">Title</label>
                                        <input type="text" name="article_title" class="form-control" value="" />
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col">
                                    <div class="form-group">
                                        <label for="article_tags">Tags</label>
                                        <input type="text" name="article_tags" class="form-control" value="" />
                                    </div>                 
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-6 text-center">
                                    <div class="form-group">
                                        <label for="article_description">Description</label>
                                        <textarea id="article_description" name="article_description" class="form-control" cols="30" rows="10"></textarea>
                                    </div>                                    
                                </div>

                                <div class="col-6">
                                    <div id="article-description-markdown">
        
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-6 text-center">
                                    <div class="form-group">
                                        <label for="article_contents">Contents</label>
                                        <textarea id="article_contents" name="article_contents" class="form-control" cols="50" rows="20"></textarea>
                                    </div>                                    
                                </div>
                                <div class="col-6">
                                    <div id="article-contents-markdown">
        
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col">
                                    <div class="form-group">
                                        <label for="article_image">Image</label>
                                        <input type="file" id="article-image" name="article_image" class="form-control" />
                                    </div>                           
                                </div>
                            </div>

                            <div class="text-center" id="article_save">
                                <button class="btn btn-primary post-btn" type="submit">Add Article!</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% else %}
        <p><h3 class="text-center">You are not authorized.</h3></p>
{% endif %}
    